### ISSUE TITLE
Does report-generation work well for you?

### ISSUE THREAD

**Issue by zhtaoang** [jan-molak/serenity-js-getting-started#1]
Not sure if it's something I did that was wrong, or it's actually defective, but I tried the examples in serenity-js project  neither running "npm run report" nor using "the failsafe" produces the correct report, which means the report get generated but will be marking the test as "Untested" and missing all the details no matter the tests ran previously were passed or failed. And I followed the instructions from the tutorial project (serenity-js-getting-started) with the same behavior. I wonder if I did something wrong or it's my computer with the latest Java and Node and NPM and browsers (it did run with my current chrome browser though).

**Comment by jan-molak** [comment]
Hey @zhtaoang - it's hard to tell without seeing the code. If you're seeing the issue with the serenity-js-getting-started, perhaps you could push your code to github so that I could have a look?

**Comment by zhtaoang** [comment]
Hi @jan-molak - I checked out your 2-reports branch, and it worked beautifully ... so I guess that was me all along, must have missed something along the way ... anyway, thank you very much for replying to me back so quickly, and sorry that it was a false alarm ... please close the issue or delete it, I would have done that had I found a way to delete it myself. Thanks again!

**Comment by jan-molak** [comment]
No problem at all, always happy to help! Have fun with Serenity/JS and please let me know should you find any problems :-)
