### ISSUE TITLE
Cannot find module 'protractor/globals'

### ISSUE THREAD

**Issue by tremkonzah** [jan-molak/serenity-js-getting-started#2]
Getting an error `Cannot find module 'protractor/globals'` when following your instruction to 
`import { protractor } from 'protractor/globals';`

no luck when i change to `import { protractor } from 'protractor';`

**Comment by tremkonzah** [comment]
i did changes in serenity-js/lib/serenity-protractor/screenplay/interactions/select.js to

`var globals_1 = require('protractor');`

npm test executed successfull

**Comment by jan-molak** [comment]
Thanks! Protractor has changed its public api between 4.0.8 and 4.0.9.. I'll update the docs shortly.

**Comment by jan-molak** [comment]
Thanks for reporting the issue, it should be addressed in the latest Serenity/JS. Please let me know should you come across any other problems!

Best,
Jan
